export interface JournalArticle {
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  readTime: string;
  date: string;
  image: string;
  content: string[];
}

export const JOURNAL: JournalArticle[] = [
  {
    slug: 'le-spitz-nain-une-histoire-de-tendresse',
    title: "Le Spitz Nain, une Histoire de Tendresse : Des Palais Royaux aux Plages de la Côte d'Azur",
    excerpt:
      "Du salon de la reine Victoria aux plages de Pampelonne, le Pomeranian a traversé les siècles avec une élégance et une malice que rien ne semble pouvoir altérer. Retour sur l'histoire fascinante du Spitz nain — et sur ce qui en fait un compagnon à part entière.",
    category: 'Notre passion',
    readTime: '5 min',
    date: '2026-04-15',
    image: 'https://res.cloudinary.com/dci5mreqo/image/upload/v1777834078/Votre_texte_de_paragraphe_1600_x_1350_px_1600_x_900_px_1500_x_900_px_faq2ro.png',
    content: [
      "Il y a des chiens qu'on remarque, et des chiens qu'on n'oublie pas. Le <strong>Spitz nain</strong> appartient résolument à la seconde catégorie. Avec son pelage en auréole, ses petites oreilles dressées et son regard pétillant d'intelligence, le <strong>Pomeranian</strong> ne laisse personne indifférent. Mais derrière cette silhouette iconique se cache bien plus qu'un simple compagnon de vie : une histoire riche de plusieurs siècles, une personnalité hors du commun, et une relation à l'humain d'une profondeur rare. Chez <strong>Maison Pomeranian</strong>, c'est cette histoire-là que nous aimons raconter — et cette relation-là que nous cherchons à honorer, jusque dans les moindres détails du quotidien.",

      "<h2>Des Neiges de Poméranie aux Salons Européens</h2>Pour comprendre le <strong>Pomeranian</strong> d'aujourd'hui, il faut remonter aux origines de la race — bien loin des plages ensoleillées de la Côte d'Azur. Le <strong>Spitz nain</strong> tire son nom de la <strong>Poméranie</strong>, une région historique s'étendant sur le nord de l'Allemagne et de la Pologne actuelles, bordée par la mer Baltique. Dans ces contrées au climat rigoureux, ses ancêtres — bien plus grands et robustes qu'aujourd'hui — étaient utilisés comme chiens de traîneau, de garde et de berger. Leur <strong>double pelage dense</strong>, leur résistance au froid et leur vigilance naturelle en faisaient des travailleurs précieux. Au fil des siècles et des sélections, la race fut progressivement miniaturisée pour répondre à un nouveau rôle : celui de <strong>chien de compagnie</strong> dans les cours royales et les salons bourgeois d'Europe. Le Spitz nain devint alors ce qu'il est resté jusqu'à aujourd'hui : une présence lumineuse, élégante, et dotée d'un caractère bien affirmé.",

      "<h2>La Reine Victoria et la Naissance d'une Légende</h2>Aucune figure n'a davantage contribué à façonner le <strong>Pomeranian</strong> moderne que la <strong>reine Victoria d'Angleterre</strong>. Au cours d'un voyage en Italie en 1888, la souveraine tomba éperdument amoureuse d'un petit Spitz prénommé Marco — un chien au pelage roux doré, remarquablement petit pour l'époque. Elle le ramena à la cour de Buckingham, et ce coup de foudre royal allait changer à jamais le destin de la race. Victoria se passionna pour l'élevage du <strong>Spitz nain</strong> et contribua activement à réduire encore sa taille, passant d'environ 13 kg à moins de 3 kg pour les spécimens les plus fins. Elle exposait ses chiens lors des concours canins britanniques — et remportait régulièrement les plus hautes distinctions. Sa passion déclencha une véritable mode dans la haute société européenne : avoir un <strong>Pomeranian</strong> devint un signe distinctif de raffinement et de bon goût. Une réputation que la race n'a jamais vraiment perdue.",

      "<h2>Un Caractère Aussi Grand que son Pelage</h2>Ce qui frappe, chez le <strong>Spitz nain</strong>, c'est le décalage presque comique entre sa taille et sa personnalité. Le <strong>Pomeranian</strong> est un grand chien dans un petit corps — et il le sait. Curieux de tout, intrépide, souvent le premier à explorer une situation nouvelle, il observe le monde avec une intensité qui surprend toujours. <strong>Intelligent et vif d'esprit</strong>, il apprend rapidement, aime les défis, et peut se montrer étonnamment tenace lorsqu'il a décidé de quelque chose. Cette détermination est parfois qualifiée de caprice — mais c'est avant tout le reflet d'un chien qui a des opinions, et qui n'hésite pas à les exprimer. Il est aussi profondément <strong>attaché à ses humains</strong> : fidèle, expressif, capable d'une tendresse désarmante. Il aime la compagnie, les câlins, et les moments de complicité partagée. C'est un chien qui vit pleinement — et qui vous le fait sentir.",

      "<h2>Le Pomeranian Aujourd'hui : Entre Héritage et Art de Vivre</h2>Des palais victoriens aux plages de <strong>Pampelonne</strong>, des ruelles de Montmartre aux terrasses de Saint-Tropez — le <strong>Pomeranian</strong> a suivi ses propriétaires partout où la vie était belle. Il s'est imposé comme l'un des chiens de compagnie les plus populaires au monde, chéri par des célébrités, des artistes, des familles, et tous ceux qui reconnaissent en lui quelque chose d'unique : une présence à la fois légère et intense, douce et affirmée. Aujourd'hui, le <strong>Spitz nain</strong> est aussi une icône des réseaux sociaux, une star de l'esthétique contemporaine — et pourtant, il reste fondamentalement le même qu'au temps de la reine Victoria : un être à part, qui mérite d'être traité comme tel. Prendre soin d'un <strong>Pomeranian</strong>, c'est prendre soin d'un héritage vivant.",

      "<h2>La Philosophie Maison Pomeranian : Aimer jusqu'aux Détails</h2>C'est de cette conviction qu'est née <strong>Maison Pomeranian</strong>. Nous croyons qu'aimer un <strong>Loulou</strong>, c'est aller au-delà de l'affection — c'est lui offrir un cadre de vie pensé pour lui, des soins à la hauteur de ses besoins spécifiques, et des accessoires qui respectent à la fois son confort et son caractère. Du tapis sur lequel il se couche, à la brosse qui démêle en douceur son <strong>sous-poil</strong>, chaque détail compte. Parce qu'un <strong>Spitz nain</strong> épanoui, c'est un chien dont le pelage respire, dont la peau est nourrie, et dont chaque séance de brossage est un moment de tendresse et non une corvée. C'est tout le sens de notre <a href='/collections/soins-cosmetiques' class='text-orose-500 underline underline-offset-2 hover:text-orose-600 transition-colors'>collection de soins cosmétiques</a>.",

      "<h2>Un Compagnon pour la Vie — et au-delà</h2>Ce qui rend le <strong>Pomeranian</strong> si spécial, c'est peut-être cela : il ne se contente pas de partager votre quotidien. Il l'enrichit. Il vous apprend la patience, la régularité, l'attention aux détails. Il vous rappelle que les plus grandes joies tiennent souvent dans les plus petits gestes — une séance de brossage apaisante, un regard complice, une promenade au lever du soleil. Chez <strong>Maison Pomeranian</strong>, nous avons fait de ces gestes notre mission. Parce que derrière chaque <strong>Spitz nain</strong> se cache une histoire d'amour — et que cette histoire mérite les meilleurs soins, les plus beaux accessoires, et toute l'attention du monde. Votre Loulou le mérite — et notre <a href='/collections/soins-cosmetiques' class='text-orose-500 underline underline-offset-2 hover:text-orose-600 transition-colors'>collection de soins cosmétiques</a> est là pour le prouver.",
    ],
  },
  {
    slug: 'soin-pelage-spitz-routine-douceur',
    title: "L'Art de Prendre Soin du Pelage de votre Spitz : Rituel Complet et Conseils d'Expert",
    excerpt:
      "Brossage, mue, bain, séchage… Le pelage double du Pomeranian est sa plus belle signature — et son plus grand défi. Découvrez notre rituel complet pour un Spitz nain soyeux et épanoui toute l'année.",
    category: 'Soins',
    readTime: '7 min',
    date: '2026-04-08',
    image: 'https://res.cloudinary.com/dci5mreqo/image/upload/v1777834077/Votre_texte_de_paragraphe_1600_x_1350_px_1600_x_900_px_1500_x_900_px_3_vztxlb.png',
    content: [
      "Il y a quelque chose de presque magique dans le pelage d'un <strong>Pomeranian</strong>. Cette auréole de fourrure dense, brillante, qui semble défier les lois de la gravité… Ce n'est pas un hasard si le <strong>Spitz nain</strong> est l'une des races les plus photographiées au monde. Mais derrière cette beauté spectaculaire se cache une réalité que tout propriétaire doit intégrer dès le premier jour : le <strong>pelage Pomeranian</strong> est une merveille qui demande de l'attention, de la régularité, et les bons gestes. Mal entretenu, il se noue, s'emmêle, et peut devenir source d'inconfort pour votre Loulou. Bien soigné, il révèle tout son éclat — et chaque brossage devient un moment de complicité.",

      "<h2>Comprendre la Structure Unique du Pelage Pomeranian</h2>Avant de parler de rituel, il faut comprendre ce que l'on entretient. Le <strong>pelage du Spitz nain</strong> est dit <strong>double robe</strong> : une architecture en deux couches distinctes, chacune jouant un rôle précis. Le <strong>sous-poil</strong> est dense, doux et duveteux. C'est lui qui assure la thermorégulation du chien — isolation contre le froid en hiver, barrière contre la chaleur en été. Il est aussi la principale source de nœuds et d'emmêlements lorsqu'il n'est pas entretenu régulièrement. Le <strong>jarre</strong>, quant à lui, est constitué de poils plus longs, plus raides et brillants. C'est lui qui donne au Pomeranian ce volume si caractéristique et cette silhouette reconnaissable entre mille. C'est aussi lui qui reflète la lumière et donne cet aspect soyeux et lumineux que l'on admire tant. Cette double structure impose une approche de soins spécifique : on ne brosse pas un <strong>Spitz nain</strong> comme on brosserait un Labrador ou un Beagle. Chaque geste compte, chaque outil a son importance.",

      "<h2>Le Brossage : Pilier de la Routine Soin Pomeranian</h2><h3>La fréquence idéale selon la saison</h3>La régularité est la clé d'un <strong>pelage Pomeranian</strong> en pleine santé. En dehors des périodes de mue, un <strong>brossage doux trois fois par semaine</strong> est suffisant pour maintenir le pelage démêlé, aéré et brillant. Pendant les <strong>périodes de mue saisonnière</strong> — au printemps et en automne — le sous-poil se renouvelle massivement. Le brossage doit alors passer à une <strong>fréquence quotidienne</strong> pour accompagner ce renouvellement naturel, éviter la formation de nœuds, et limiter les poils perdus sur vos meubles et vêtements.",

      "<h3>Les bons gestes pour un brossage réussi</h3>Le brossage d'un <strong>Spitz nain</strong> n'est pas un geste anodin. Il doit être lent, méthodique, et toujours réalisé <strong>dans le sens du poil</strong>. Commencez par le corps, en travaillant section par section, avant de passer aux zones plus sensibles comme les oreilles, les pattes, et la queue. Utilisez une <strong>brosse à picots en laiton</strong> pour le jarre : ses dents souples démêlent sans arracher ni casser les poils. Complétez avec un <strong>peigne à dents larges</strong> pour travailler en profondeur le sous-poil dense. Le geste doit rester fluide, jamais brusque. Si vous rencontrez un nœud, ne tirez pas : maintenez la base du poil avec l'autre main pour éviter de tirer sur la peau, et démêlez progressivement du bout vers la racine. Ce moment de soin est aussi un moment de lien. Votre <strong>Pomeranian</strong> qui accepte le brossage avec sérénité, c'est un chien qui fait confiance — et cette confiance se construit séance après séance.",

      "<h2>Mue du Pomeranian : Comment Passer Cette Période sans Stress</h2>La <strong>mue du Spitz nain</strong> est un phénomène impressionnant. En quelques semaines, le sous-poil se renouvelle presque intégralement — et les poils perdus semblent se multiplier à l'infini. Pas de panique : c'est un processus naturel et sain, à condition de bien l'accompagner. Pendant cette période, augmentez la fréquence de brossage à chaque jour. Utilisez un <strong>démêlant adapté</strong> pour faciliter le passage de la brosse sans traumatiser le pelage fragilisé. Évitez de tirer sur les touffes de sous-poil qui se détachent : laissez-les venir naturellement au brossage. Pensez aussi à inspecter régulièrement les zones à risque : derrière les oreilles, sous les aisselles, à l'arrière des pattes — là où les nœuds se forment en premier. Certains soins spécifiques aident à faciliter la mue en nourrissant le follicule pileux et en accélérant le renouvellement. Nos <a href='/collections/soins-cosmetiques' class='text-orose-500 underline underline-offset-2 hover:text-orose-600 transition-colors'>soins cosmétiques</a> ont été pensés pour ça.",

      "<h2>Faut-il Tondre son Pomeranian en Été ?</h2>C'est l'une des questions les plus fréquentes — et l'une des idées reçues les plus tenaces. La réponse est claire : <strong>non, il ne faut pas tondre un Spitz nain</strong>, même en plein été. Cette intuition, bien qu'elle parte d'une bonne intention, peut avoir des conséquences durables sur la santé du pelage. La <strong>double robe du Pomeranian</strong> n'est pas uniquement un manteau contre le froid : c'est aussi un bouclier thermique naturel contre la chaleur, et une protection contre les rayons UV. En la supprimant, vous exposez la peau directement au soleil, augmentez le risque de brûlures cutanées, et perturbez le cycle naturel de pousse des poils. Dans certains cas, le pelage ne repousse jamais complètement de façon identique — un phénomène connu sous le nom de <strong>syndrome post-tonte</strong>, particulièrement documenté chez les Spitz. La bonne alternative à la tonte ? Un entretien régulier du sous-poil pour l'aérer, et des <strong>soins adaptés à la saison chaude</strong> pour maintenir la peau hydratée et le pelage léger.",

      "<h2>Le Bain du Pomeranian : Fréquence, Produits et Technique</h2>Contrairement aux idées reçues, le <strong>Pomeranian</strong> n'a pas besoin de bains très fréquents. <strong>Une fois par mois</strong> est une fréquence idéale pour la majorité des chiens de cette race, hors situation particulière (chien très actif en extérieur, allergie cutanée, etc.). Trop de bains dessèchent le cuir chevelu, fragilisent le sous-poil, et déséquilibrent le film protecteur naturel de la peau. Pour le choix du produit, privilégiez un <strong>shampoing doux à pH neutre</strong>, formulé spécifiquement pour les chiens. Les shampoings humains — même les plus doux — ont un pH inadapté à la peau animale et peuvent provoquer des irritations. Côté technique : mouillez le pelage en profondeur en commençant par les pattes et en remontant, appliquez le shampoing en massant délicatement le sous-poil avec le bout des doigts, rincez abondamment (tout résidu de produit peut provoquer des démangeaisons), et séchez d'abord avec une <strong>serviette en coton absorbante</strong> avant de terminer au <strong>sèche-cheveux à température tiède</strong>. Ne frottez jamais : tapotez. La chaleur du sèche-cheveux, combinée à un brossage final, révèle tout le volume et la légèreté naturelle du <strong>pelage Spitz nain</strong>.",

      "<h2>Les Soins Complémentaires à Ne Pas Négliger</h2>L'entretien du <strong>pelage Pomeranian</strong> ne s'arrête pas au brossage et au bain. D'autres soins réguliers complètent la routine pour assurer un confort global à votre Loulou. Les <strong>oreilles</strong> doivent être inspectées et nettoyées régulièrement : le pelage dense autour des oreilles favorise l'accumulation de chaleur et d'humidité, terreau idéal pour les infections. Les <strong>coussinets</strong> méritent également une attention particulière, surtout en été sur le bitume chaud ou en hiver sur les routes salées : un soin hydratant protecteur les maintient souples et résistants. Enfin, les <strong>yeux</strong> du Spitz nain, expressifs et légèrement proéminents, peuvent accumuler de petits dépôts qu'il convient de nettoyer en douceur avec un soin oculaire adapté. Notre <a href='/collections/soins-cosmetiques' class='text-orose-500 underline underline-offset-2 hover:text-orose-600 transition-colors'>collection de soins cosmétiques</a> est là pour vous aider à faire les bons choix.",

      "<h2>Faire du Soin un Moment de Complicité</h2>Le plus beau rituel n'est pas celui qui donne le pelage le plus brillant — c'est celui que votre <strong>Pomeranian</strong> attend avec impatience. Un chien détendu pendant le brossage, c'est un chien qui associe ce moment à quelque chose de positif. Prenez le temps, parlez-lui doucement, récompensez sa patience. Avec de la régularité et les bons outils, prendre soin du <strong>pelage de votre Spitz nain</strong> cesse d'être une contrainte pour devenir ce qu'il devrait toujours être : un moment de tendresse partagée, et la plus belle façon de lui dire que vous l'aimez.",
    ],
  },
  {
    slug: 'ete-tropezien-pomeranian-rester-au-frais',
    title: "Été Tropézien : Nos Secrets pour Garder votre Loulou au Frais",
    excerpt:
      "Chaleur écrasante, bitume brûlant, coup de chaleur… Le Pomeranian et son double pelage sont plus vulnérables qu'on ne le croit face aux étés de la Côte d'Azur. Rituels, réflexes et soins indispensables pour un été serein.",
    category: 'Lifestyle',
    readTime: '5 min',
    date: '2026-03-22',
    image: 'https://res.cloudinary.com/dci5mreqo/image/upload/v1777834078/Votre_texte_de_paragraphe_1600_x_1350_px_1600_x_900_px_1500_x_900_px_1_xri8dr.png',
    content: [
      "Le soleil qui baigne Saint-Tropez, les terrasses animées, la lumière dorée sur la Méditerranée… L'été sur la Côte d'Azur est une promesse de douceur de vivre. Mais pour votre <strong>Pomeranian</strong>, cette même saison peut rapidement devenir une épreuve. Derrière ce pelage abondant et spectaculaire se cache une réalité méconnue : le <strong>Spitz nain</strong> est l'une des races les plus sensibles à la chaleur. Un risque à ne pas prendre à la légère — et une raison de plus d'adopter les bons réflexes dès les premiers beaux jours.",

      "<h2>Pourquoi le Pomeranian Souffre-t-il Particulièrement de la Chaleur ?</h2>Tout est dans la physiologie. Le <strong>Spitz nain</strong> possède une <strong>double robe</strong> — un sous-poil dense et isolant, recouvert d'un jarre long et fourni. Si cette architecture capillaire est un atout formidable pour les hivers rigoureux d'Europe centrale (dont est originaire la race), elle devient un véritable piège thermique en plein été méditerranéen. Contrairement à l'humain, le chien ne transpire pas par la peau. Il régule sa température principalement <strong>par le halètement</strong> et, dans une moindre mesure, par ses coussinets. Cette capacité de thermorégulation est rapidement dépassée lorsque les températures grimpent au-delà de 28°C — un seuil atteint quotidiennement sur la Côte d'Azur en juillet et août. S'ajoute à cela la <strong>petite taille du Pomeranian</strong> : plus proche du sol, il absorbe davantage la chaleur réfléchie par le bitume ou les terrasses en pierre. La vigilance s'impose donc bien avant que votre Loulou ne montre le moindre signe de détresse.",

      "<h2>La Règle d'Or : Adapter les Sorties à la Météo</h2>Le réflexe le plus simple — et le plus efficace — reste d'<strong>adapter les horaires de promenade</strong> en fonction de la chaleur. En été, il est fortement déconseillé de sortir votre <strong>Pomeranian</strong> entre <strong>11h et 17h</strong>. Ce créneau correspond aux heures de pic thermique, où le sol emmagasine une chaleur intense et où le rayonnement solaire est maximum. Préférez les <strong>sorties tôt le matin</strong>, idéalement avant 9h, lorsque l'air est encore frais et l'ombre généreuse. Le <strong>soir après 19h</strong> est également idéal, une fois que le bitume a eu le temps de se refroidir. Pour tester si le sol est praticable, utilisez la règle des 5 secondes : posez le dos de votre main à plat sur la surface. Si vous ne pouvez pas tenir plus de 5 secondes, c'est trop chaud pour les <strong>coussinets de votre Spitz nain</strong> — et une source de brûlures réelles.",

      "<h2>Créer un Cocon de Fraîcheur à la Maison</h2>À l'intérieur, l'objectif est simple : offrir à votre <strong>Pomeranian</strong> un espace où il peut se reposer sans subir la chaleur. Plusieurs éléments peuvent transformer votre intérieur en véritable havre de fraîcheur. Investissez d'abord dans un <strong>tapis rafraîchissant</strong> : conçu avec un gel thermorégulateur activé par le poids, il maintient une surface fraîche sans avoir besoin d'être réfrigéré. Idéal pour un Loulou qui aime s'étirer. Pensez aussi à une <strong>fontaine à eau en circuit fermé</strong> : les chiens boivent davantage lorsque l'eau est fraîche et en mouvement. Une bonne hydratation est l'une des premières protections contre le coup de chaleur. Identifiez enfin le <strong>coin le plus ombragé et le plus aéré</strong> de votre logement, et installez-y son panier ou sa couverture préférée. Évitez de positionner son espace de repos face à une baie vitrée exposée au soleil, même avec la climatisation en marche.",

      "<h2>Les Soins du Pelage : un Rôle Clé en Été</h2>On aurait tendance à croire qu'il faut tondre le <strong>Pomeranian</strong> pour le rafraîchir en été. C'est une erreur courante — et potentiellement dangereuse. La double robe du <strong>Spitz nain</strong>, si elle emmagasine la chaleur, joue aussi un rôle d'<strong>isolation thermique naturelle</strong>. En la supprimant, vous exposez la peau directement aux UV, augmentez le risque de coups de soleil et perturbez durablement le cycle de pousse du pelage. La vraie solution ? Un <strong>entretien régulier et adapté</strong>. Brossez votre Pomeranian plusieurs fois par semaine pour éliminer les poils morts du sous-poil, qui forment une barrière thermique supplémentaire. Des soins hydratants et apaisants pour la peau contribuent également à réguler le confort cutané lorsque les températures s'emballent. C'est là que les <a href='/collections/soins-cosmetiques' class='text-orose-500 underline underline-offset-2 hover:text-orose-600 transition-colors'>soins cosmétiques adaptés</a> font toute la différence.",

      "<h2>Voiture, Terrasse, Plage : les Pièges à Éviter</h2>L'été rime avec déplacements et sorties — autant de situations qui peuvent exposer votre <strong>Spitz nain</strong> à des risques supplémentaires. La voiture reste le danger le plus immédiat. Même garée à l'ombre, vitre entrouverte, l'habitacle peut atteindre <strong>50°C en moins de 10 minutes</strong>. Ne laissez jamais votre Pomeranian seul dans un véhicule, même pour une course rapide. Si vous devez voyager avec lui, prévoyez une glacière avec des packs froids à placer à proximité de son transporteur, et n'hésitez pas à faire des pauses régulières à l'ombre. En terrasse, choisissez toujours une table <strong>à l'ombre</strong> et apportez sa gamelle d'eau. Certains restaurants de la Côte d'Azur proposent désormais des gamelles d'eau pour les chiens — n'hésitez pas à demander. À la plage, méfiez-vous du sable brûlant et du soleil direct : limitez les expositions, évitez les heures chaudes, et hydratez-le régulièrement.",

      "<h2>Reconnaître et Réagir face à un Coup de Chaleur</h2>Malgré toutes les précautions, un coup de chaleur peut survenir. Savoir le reconnaître est essentiel. Les signes d'alerte chez le <strong>Pomeranian</strong> : un <strong>halètement excessif et rapide</strong>, une <strong>langue très rouge ou violacée</strong>, une <strong>démarche hésitante ou une prostration</strong>, des vomissements, ou une perte de conscience. Face à ces symptômes, chaque minute compte. Commencez par <strong>mettre votre Loulou à l'ombre</strong> immédiatement. Humidifiez son pelage avec de l'<strong>eau tiède — jamais glacée</strong>, car un choc thermique trop brutal peut aggraver la situation. Placez des linges humides sur ses coussinets, ses aisselles et son ventre, zones où la chaleur se dissipe le mieux. Appelez votre vétérinaire sans attendre et dirigez-vous en urgence vers la clinique la plus proche. N'attendez pas que la situation s'améliore d'elle-même.",

      "<h2>La Beauté du Pelage, Même en Plein Été</h2>Un <strong>Pomeranian</strong> bien soigné en été, c'est un chien confortable, serein, et toujours aussi élégant. Parce que l'entretien du pelage ne s'arrête pas avec la chaleur — il s'adapte. Des brossages plus fréquents, des soins hydratants ciblés, et une routine pensée pour la saison : voilà les piliers d'un été réussi pour votre Loulou. Vous trouverez tout ce qu'il faut dans notre <a href='/collections/soins-cosmetiques' class='text-orose-500 underline underline-offset-2 hover:text-orose-600 transition-colors'>collection de soins cosmétiques</a>. Parce qu'un Loulou épanoui, même sous le soleil de Saint-Tropez, mérite ce qu'il y a de plus doux.",
    ],
  },
  {
    slug: 'voyager-avec-son-spitz-rituels-elegance',
    title: "Voyager avec son Pomeranian : Guide Complet pour des Escapades Réussies",
    excerpt:
      "Sac de transport, check-list, train, avion… Tout ce qu'il faut savoir pour voyager avec votre Spitz nain en gardant style, sérénité et bien-être animal.",
    category: 'Voyage',
    readTime: '6 min',
    date: '2026-03-10',
    image: 'https://res.cloudinary.com/dci5mreqo/image/upload/v1777834078/Votre_texte_de_paragraphe_1600_x_1350_px_1600_x_900_px_1500_x_900_px_2_pyjo9p.png',
    content: [
      "Voyager avec un <strong>Pomeranian</strong>, c'est partager un secret : celui de toujours avoir avec soi un compagnon discret, élégant, et indéniablement craquant. Mais derrière cette image de carte postale se cache une organisation rigoureuse. Un <strong>Spitz nain</strong> mal préparé au voyage, c'est un chien stressé — et un propriétaire épuisé. Voici tout ce qu'il faut savoir pour partir l'esprit léger, avec les bons <strong>accessoires Pomeranian</strong> et une routine de soin adaptée.",
  
      "<h2>Choisir le Bon Sac de Transport pour votre Spitz Nain</h2>Le sac de transport est l'élément central de tout voyage avec un <strong>Pomeranian</strong>. Choisissez-le bien aéré, avec une base rigide pour le confort, et juste assez grand pour qu'il puisse se retourner sans flotter dedans. Les modèles en toile cirée et cuir tannage végétal vieillissent magnifiquement et résistent à l'usage intensif. Évitez les sacs trop grands : un espace excessif est source d'anxiété pour les petites races. Parmi les <strong>accessoires Spitz</strong> indispensables, le sac de transport est sans doute celui qui demande le plus de soin dans le choix.",
  
      "<h2>La Trousse de Voyage Indispensable pour votre Pomeranian</h2>Ne partez jamais sans : eau fraîche et gamelle pliable, quelques friandises de réconfort, sa brosse habituelle — la continuité des <a href='/collections/soins-cosmetiques' class='text-orose-500 underline underline-offset-2 hover:text-orose-600 transition-colors'><strong>soins Pomeranian</strong></a> est rassurante pour lui — son jouet préféré (un repère olfactif puissant contre le stress), une serviette douce, et son carnet de santé à jour. Pour les voyages de plus d'une journée, ajoutez ses produits de toilettage habituels : un pelage entretenu même en déplacement, c'est un chien plus à l'aise et plus serein. Le <strong>Soin Splitz</strong> en format voyage est particulièrement pratique pour maintenir le double manteau du Spitz en pleine santé, même loin de la maison.",
  
      "<h2>Soin Splitz en Voyage : Pourquoi Ne Jamais l'Oublier</h2>Beaucoup de propriétaires de <strong>Pomeranian</strong> négligent les <strong>soins Pomeranian</strong> pendant les vacances. C'est une erreur. Le pelage double du Spitz nain continue de s'emmêler, de muer, et de nécessiter une attention quotidienne — même à l'hôtel ou chez des amis. Le <strong>Soin Splitz</strong> est justement conçu pour s'intégrer facilement dans n'importe quelle routine de voyage : léger, efficace, formulé spécifiquement pour le double manteau du Spitz. Un brossage rapide chaque soir avec un spray démêlant suffit à éviter les nœuds tenaces qui s'installent en quelques jours d'inattention.",
  
      "<h2>Voyager en Train ou en Avion avec un Spitz Nain</h2>Pour les <strong>déplacements en train</strong>, anticipez : la SNCF demande un billet spécifique pour les chiens transportés en sac. En <strong>avion</strong>, vérifiez les conditions propres à chaque compagnie — les <strong>Spitz nains de moins de 6 kg</strong> peuvent généralement voyager en cabine dans un sac homologué placé sous le siège. Au-delà, ils voyagent en soute dans des conditions plus stressantes. Anticipez ces démarches plusieurs semaines avant le départ.",
  
      "<h2>Les Accessoires Spitz Indispensables pour Voyager Sereinement</h2>Au-delà du sac de transport, certains <strong>accessoires Spitz</strong> font toute la différence en voyage. Un tapis de voyage familier pour recréer un espace rassurant dans un environnement inconnu. Une fontaine à eau pliable pour l'hydratation pendant les transports. Un harnais confortable pour les promenades dans des villes inconnues. Et bien sûr, une brosse à picots et un peigne à dents larges pour maintenir les <strong>soins Pomeranian</strong> quotidiens. Retrouvez tous nos <a href='/collections/soins-cosmetiques' class='text-orose-500 underline underline-offset-2 hover:text-orose-600 transition-colors'><strong>accessoires Pomeranian</strong> de voyage</a> sélectionnés avec la même exigence que celle que vous portez à votre compagnon.",
  
      "<h2>Adapter l'Alimentation et l'Hydratation en Déplacement</h2>Le stress du voyage peut perturber l'appétit de votre <strong>Pomeranian</strong>. Maintenez ses horaires habituels autant que possible, et emportez sa nourriture habituelle plutôt que de changer de marque en cours de route. L'hydratation est particulièrement importante : un Spitz déshydraté est un Spitz dont le pelage souffre. Proposez-lui de l'eau fraîche toutes les deux heures pendant les longs trajets. Si votre Loulou est sujet au stress lors des voyages, quelques gouttes d'un complément naturel apaisant peuvent faire la différence — à demander à votre vétérinaire.",
  
      "<h2>Préparer votre Pomeranian au Voyage : Les Étapes Clés</h2>La préparation commence bien avant le départ. Quelques semaines à l'avance, habituez votre <strong>Spitz nain</strong> à son sac de transport en le laissant y dormir à la maison. Le jour J, évitez de le nourrir deux heures avant le départ pour limiter les nausées. Prévoyez une promenade calme avant de partir pour qu'il soit détendu. Et n'oubliez pas : votre propre sérénité se transmet à votre chien. Un propriétaire stressé, c'est un <strong>Pomeranian</strong> stressé. Arrivez à l'avance, organisez-vous, et profitez du voyage.",
  
      "<h2>La Philosophie Maison Pomeranian : Voyager avec Élégance</h2>Chez <strong>Maison Pomeranian</strong>, nous croyons que voyager avec son Loulou ne devrait jamais être une contrainte — mais une extension naturelle de votre art de vivre. Avec les bons <strong>accessoires Spitz</strong>, le <strong>Soin Splitz</strong> en format voyage, et quelques habitudes bien rodées, chaque escapade devient une aventure partagée. Découvrez <a href='/collections/soins-cosmetiques' class='text-orose-500 underline underline-offset-2 hover:text-orose-600 transition-colors'>notre sélection complète de soins et accessoires Pomeranian</a> pour des escapades aussi élégantes que sereines.",
    ],
  },
  {
    slug: 'entretien-pelage-spitz-nain-guide-complet',
    title: 'Pelage du Spitz Nain : le Guide Complet pour un Double Manteau Soyeux',
    excerpt:
      'Brossage, bain, mue, alopécie X : notre guide expert pour entretenir le double manteau de votre Pomeranian. Conseils, techniques et produits sélectionnés avec amour.',
    category: 'Soins',
    readTime: '8 min',
    date: '2026-05-03',
    image: 'https://res.cloudinary.com/dci5mreqo/image/upload/v1777834683/Votre_texte_de_paragraphe_1600_x_1350_px_1600_x_900_px_1500_x_900_px_4_u8kcws.png',
    content: [
      "Votre Pomeranian est magnifique. Ce pelage abondant, ce double manteau qui le fait ressembler à un petit lion nordique, c'est sa signature. Mais ce même pelage peut vite devenir votre cauchemar. Nœuds tenaces, mue interminable, sous-poil emmêlé… Sans routine adaptée, le pelage de votre Spitz souffre. Et lui aussi.",
      "Le pelage du Pomeranian se compose de deux couches distinctes. Le sous-poil : dense, duveteux et isolant, c'est lui qui régule la température de votre compagnon. La robe de garde : longue, brillante, légèrement rigide. Elle protège contre l'humidité et les agressions extérieures. C'est cette architecture unique, le double manteau, qui donne au Spitz son volume caractéristique.",
      "Attention à l'erreur la plus fréquente : tondre le Spitz en été pour le 'rafraîchir'. C'est contre-productif. Le double manteau l'isole autant du chaud que du froid. Une tonte peut déclencher une alopécie X : repousse anormale et perte définitive de texture.",
      "Concernant le brossage : en dehors des périodes de mue, trois fois par semaine minimum. Pendant la mue, au printemps et en automne, quotidiennement. Travaillez par sections en partant des pattes arrière vers la tête. Soulevez le poil à contre-sens avec une brosse à picots, puis lissez dans le sens de pousse. Démêlez le sous-poil avec un peigne à dents longues avant de passer la brosse. N'arrachez jamais — si vous rencontrez un nœud, utilisez un démêlant et travaillez-le avec les doigts d'abord.",
      "Pour les produits de soin quotidien, <a href='/collections/soins-cosmetiques' class='text-orose-500 underline underline-offset-2 hover:text-orose-600 transition-colors'>notre gamme de soins premium</a> a été formulée spécifiquement pour les pelages doubles des Spitz. Les outils indispensables : brosse à picots laiton pour le volume et le sous-poil, peigne à dents fines et larges pour détecter les nœuds cachés, carde pour les périodes de mue intense, spray démêlant à appliquer avant le brossage sur poil légèrement humide.",
      "Le bain : une fois par mois suffit. Un bain trop fréquent décape le film protecteur naturel du pelage et fragilise le sous-poil. Utilisez exclusivement <a href='/products/shampoing-art-de-vivre' class='text-orose-500 underline underline-offset-2 hover:text-orose-600 transition-colors'>un shampoing adapté au double manteau</a>, à pH neutre entre 6,5 et 7,5. Pour les Pomeranians, privilégiez les formules hydratantes pour nourrir le sous-poil dense, les shampoings démêlants pour faciliter le brossage post-bain, et les formules sans sulfate pour préserver la brillance de la robe de garde.",
      "Le séchage est l'étape la plus importante et la plus négligée. Absorbez l'excès d'eau avec une serviette en coton doux, sans frotter. Séchez au sèche-cheveux à température tiède, jamais chaude, en brossant simultanément. Séchez toujours en soulevant le poil, jamais à plat, sous peine de créer des feutres dans le sous-poil. Un Spitz séché incomplètement développe des nœuds profonds qui ne se défont qu'en coupant.",
      "Deux fois par an, votre Pomeranian entre en mue. Le sous-poil se renouvelle intégralement. Signes d'une mue active : poils qui s'arrachent par touffes au brossage, aspect cotonneux de la robe, démangeaisons légères. Protocole : brossage quotidien à la carde puis au peigne, bain en milieu de mue pour aider au déchaussement, <a href='/collections/soins-cosmetiques' class='text-orose-500 underline underline-offset-2 hover:text-orose-600 transition-colors'>spray démêlant</a> avant chaque séance.",
      "L'alopécie X, ou Black Skin Disease, est une condition spécifique aux Spitz nordiques. Elle se manifeste par une perte de poil symétrique, sans démangeaison, débutant souvent sur le dos et les cuisses. Si vous observez une perte de poil anormale, consultez un vétérinaire dermatologue avant d'envisager tout traitement.",
      "Entretenir le pelage de votre Spitz Nain, c'est bien plus qu'une question d'esthétique. C'est prendre soin de sa santé cutanée, de son confort, et de votre lien. Brossez trois fois par semaine minimum, baignez une fois par mois avec un shampoing adapté, séchez toujours complètement en soulevant le poil. Et surtout ne tondez jamais. <a href='/collections/soins-cosmetiques' class='text-orose-500 underline underline-offset-2 hover:text-orose-600 transition-colors'>Découvrez tous nos produits de toilettage</a> pour accompagner votre Loulou au quotidien.",
    ],
  },
  {
    slug: 'soin-splitz-pomeranian',
    title: "Le Soin Splitz : Le Secret d'un Pelage de Pomeranian Impeccable",
    excerpt:
      "Nœuds tenaces, sous-poil difficile, produits inadaptés… Le Soin Splitz est la réponse formulée spécifiquement pour le pelage unique du Spitz nain. Guide complet et conseils d'expert.",
    category: 'Soins',
    readTime: '6 min',
    date: '2026-05-05',
    image: 'https://res.cloudinary.com/dci5mreqo/image/upload/v1777834683/Votre_texte_de_paragraphe_1600_x_1350_px_1600_x_900_px_1500_x_900_px_4_u8kcws.png',
    content: [
      "Votre <strong>Spitz nain</strong> passe des heures à se faire admirer… mais son pelage, lui, réclame une attention toute particulière. Les nœuds s'accumulent, le sous-poil s'épaissit, et les produits génériques du commerce ne font qu'aggraver la situation. Le résultat ? Un <strong>Pomeranian</strong> moins à l'aise, un propriétaire frustré, et des séances de brossage qui tournent au cauchemar. Il existe pourtant une solution pensée spécifiquement pour les spécificités uniques de cette race : le <strong>Soin Splitz</strong>.",

      "<h2>Pourquoi le Pomeranian a-t-il Besoin de Soins Spécifiques ?</h2>Le <strong>Spitz nain</strong> n'est pas un chien ordinaire — et son pelage non plus. Originaire de la région de Poméranie, au nord de l'Allemagne et de la Pologne actuelles, cette race a été sélectionnée pendant des siècles pour sa <strong>double robe dense et luxuriante</strong>. Une beauté qui a une contrepartie : un entretien rigoureux et des produits vraiment adaptés.",

      "C'est la <strong>reine Victoria d'Angleterre</strong> qui, au XIXe siècle, contribua à populariser le Pomeranian tel qu'on le connaît aujourd'hui. Tombée amoureuse d'un petit Spitz lors d'un voyage en Italie, elle lança une mode qui n'allait plus jamais s'éteindre. Depuis, le Pomeranian se reconnaît à son <strong>pelage abondant</strong> en double couche (sous-poil et jarre), ses <strong>petites oreilles dressées</strong> et son port de tête fier, et son <strong>caractère affirmé</strong> : intelligent, curieux, parfois capricieux, toujours attachant. Derrière cette apparence presque irréelle se cache donc une exigence bien réelle en matière de <strong>soins Pomeranian</strong>.",

      "<h2>Qu'est-ce que le Soin Splitz et Pourquoi est-il Indispensable ?</h2><h3>La formule pensée pour le Spitz nain</h3>Le <strong>Soin Splitz</strong> n'est pas un produit parmi d'autres. C'est une formule développée en tenant compte des particularités anatomiques et capillaires du <strong>Pomeranian</strong> : un pH adapté, des actifs nourrissants pour le sous-poil, et une texture qui ne surcharge pas le jarre. Ses bénéfices concrets : il <strong>démêle en douceur</strong> les nœuds les plus tenaces sans arracher les poils fragiles, <strong>nourrit le sous-poil</strong> en profondeur pour prévenir les irritations cutanées, <strong>apporte de la brillance</strong> au jarre sans l'alourdir, <strong>facilite le brossage</strong> quotidien même pendant les périodes de mue intense, et <strong>protège la peau</strong> contre la sécheresse, fréquente chez les petites races.",

      "<h3>Quand et comment utiliser le Soin Splitz ?</h3>La régularité est la clé d'un <strong>pelage Pomeranian</strong> en pleine santé. Le protocole recommandé : commencez par un <strong>brossage préalable</strong> pour démêler délicatement avant l'application et éviter d'ancrer les nœuds. Appliquez ensuite le <strong>Soin Splitz</strong> uniformément sur l'ensemble du pelage humide ou sec selon la formule choisie. Laissez agir quelques minutes pour que les actifs pénètrent le sous-poil. Rincez ou non selon la version du produit (soin lavant ou soin sans rinçage). Terminez enfin par un <strong>séchage et brossage final</strong> avec une brosse adaptée pour révéler tout l'éclat naturel du pelage. Conseil d'expert : pendant la mue saisonnière du Pomeranian (printemps et automne), augmentez la fréquence des soins pour accompagner le renouvellement du sous-poil.",

      "<h2>Soin Splitz et Accessoires Pomeranian : l'Alliance Gagnante</h2>Un bon <strong>Soin Splitz</strong> seul ne suffit pas. Pour un résultat optimal, il doit s'inscrire dans une routine de beauté complète, associée aux bons <strong>accessoires Pomeranian</strong>. Les indispensables : une <strong>brosse à picots en acier inoxydable</strong> pour démêler le jarre sans casser les poils, un <strong>peigne à dents larges</strong> idéal pour travailler le sous-poil dense, un <strong>sèche-cheveux à faible température</strong> pour un séchage en douceur après le bain, et un <strong>gant de massage</strong> pour stimuler la circulation cutanée avant l'application des soins. Tout ce dont vous avez besoin pour cette routine se trouve dans notre <a href='/collections/soins-cosmetiques' class='text-orose-500 underline underline-offset-2 hover:text-orose-600 transition-colors'>collection de soins cosmétiques</a>.",

      "<h2>La Philosophie Maison Pomeranian : Chaque Loulou Mérite le Meilleur</h2>Chez <strong>Maison Pomeranian</strong>, nous partons d'une conviction simple : aimer un Loulou, c'est prendre soin de lui <strong>jusque dans les moindres détails</strong>. Du tapis sur lequel il se couche à la brosse qui démêle son sous-poil — chaque choix compte. C'est pourquoi nous sélectionnons avec exigence chaque produit de notre gamme. Le <strong>Soin Splitz</strong> incarne cette philosophie : une formule premium, des ingrédients respectueux de la peau animale, et des résultats visibles dès la première utilisation. Parce qu'un <strong>Pomeranian</strong> épanoui, c'est un pelage sain, une peau nourrie, et un chien qui se laisse brosser avec plaisir.",

      "<h2>Les Erreurs à Éviter dans les Soins Pomeranian</h2>Même avec les meilleures intentions, certaines pratiques peuvent nuire à la santé du pelage de votre Spitz nain. Évitez d'utiliser des <strong>shampoings humains</strong> dont le pH est inadapté et dessèche la peau. Ne brossez jamais un <strong>pelage complètement sec et emmêlé</strong> — risque de casse et d'inconfort. Ne négligez pas le <strong>sous-poil</strong>, principale source de nœuds et d'irritations. N'espacez pas trop les bains : un Pomeranian se salit rapidement sous son pelage dense. Et surtout, évitez les <strong>produits génériques</strong> formulés pour toutes les races, qui ne respectent pas les spécificités du Spitz nain. Si vous ne savez pas par où commencer, notre <a href='/collections/soins-cosmetiques' class='text-orose-500 underline underline-offset-2 hover:text-orose-600 transition-colors'>page soins cosmétiques</a> est un bon point de départ.",

      "<h2>Faites du Soin Splitz le Pilier de Votre Routine</h2>Le <strong>Soin Splitz</strong> n'est pas une dépense — c'est un investissement dans le bien-être et la beauté de votre <strong>Pomeranian</strong>. Adopté régulièrement, il transforme chaque séance de brossage en un moment de complicité, et chaque sortie en une démonstration de fierté. Votre Loulou mérite ce qu'il y a de plus doux. Vous méritez des soins qui fonctionnent vraiment.",
    ],
  },
];

export function getArticleBySlug(slug: string): JournalArticle | undefined {
  return JOURNAL.find((a) => a.slug === slug);
}